.Dd $Mdocdate: August 27 2019$
.Dt XDIMMER 1
.Os
.Sh NAME
.Nm xdimmer
.Nd dim the screen and/or the keyboard backlight when idle or when ambient
light changes
.Sh SYNOPSIS
.Nm
.Op Fl a
.Op Fl b Ar brighten steps
.Op Fl d
.Op Fl k
.Op Fl n
.Op Fl p Ar percent
.Op Fl s Ar dim steps
.Op Fl t Ar timeout
.Sh DESCRIPTION
.Nm
waits
.Ar timeout
number of seconds and if no keyboard or mouse input is detected, the screen
backlight is dimmed to
.Ar percent
in
.Ar dim steps
steps, unless the
.Ar -n
option was specified.
Once keyboard or mouse input is detected, the screen backlight is restored
to its previous brightness value in
.Ar brighten steps
steps.
.Pp
On OpenBSD, if the
.Ar -k
option is used, the keyboard backlight is also dimmed to zero and restored
upon movement via the
.Xr wscons 4
interface.
.Pp
Also on OpenBSD, if the
.Ar -a
option is used and an ambient light sensor device is located via
.Xr sysctl 8 ,
screen backlight (and keyboard backlight if
.Ar -k
is used) is dimmed or brightened based on lux readings.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Change backlights according to ambient light sensor lux readings.
Currently only supported on OpenBSD.
.It Fl b Ar steps
Number of steps to take while restoring backlight.
The default is
.Dv 5
steps.
.It Fl d
Print debugging messages to stdout.
.It Fl k
Affect the keyboard backlight as well as the screen backlight.
Currently only supported on OpenBSD.
.It Fl n
Do not adjust the screen backlight when idle.
.It Fl p Ar percent
Absolute brightness value to which the backlight is dimmed.
The default is
.Dv 10
percent.
.It Fl s Ar steps
Number of steps to take while decrementing backlight.
The default is
.Dv 20
steps.
.It Fl t Ar timeout
Number of seconds to wait without receiving input before dimming.
The default is
.Dv 120
seconds.
.Sh SIGNALS
.Bl -tag -width "SIGUSR1" -compact
.It Dv SIGINT
.Nm
will exit, attempting to brighten the screen and/or keyboard before
exiting if they are currently in a dimmed state.
.Pp
.It Dv SIGUSR1
.Nm
will immediately dim the screen and/or keyboard (depending on
.Ar -k
and
.Ar -n
options).
.Pp
.It Dv SIGUSR2
.Nm
will immediately brighten the screen and/or keyboard if they are
in a dimmed state.
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
