.Dd $Mdocdate: July 25 2016$
.Dt XDIMMER 1
.Os
.Sh NAME
.Nm xdimmer
.Nd dim the screen (and possibly the keyboard) backlight when idle
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl k
.Op Fl p Ar percent
.Op Fl s Ar steps
.Op Fl t Ar timeout
.Sh DESCRIPTION
.Nm
waits
.Ar timeout
number of seconds and if no keyboard or mouse input is detected, the screen
backlight is dimmed to
.Ar percent
in
.Ar steps
steps.
Once keyboard or mouse input is detected, the screen backlight is restored
to its previous brightness value.
.Pp
On OpenBSD, if the
.Ar -k
option is used, the keyboard backlight is also dimmed and restored via the
.Xr wscons 4
interface.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Print debugging messages to stdout.
.It Fl k
Affect the keyboard backlight as well as the screen backlight.
Currently only supported on OpenBSD.
.It Fl p Ar percent
Absolute brightness value to which the backlight is dimmed.
The default is
.Dv 10
percent.
.It Fl t Ar steps
Number of steps to take while decrementing backlight.
The default is
.Dv 20
steps.
.It Fl t Ar timeout
Number of seconds to wait without receiving input before dimming.
The default is
.Dv 120
seconds.
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
